name: my-app

tenantId:
keyVaultName:
keyVaultIdentity:
workloadIdentity: 

securityContext:
  pod:
    runAsNonRoot: true
    runAsUser: 1000
  container:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

image:
  registry:
  repository:
  tag: latest

# nodepool that will be used as toleration
nodepool: ""

# Default values used by many resources
host: ""
labels: {}
tolerations: []
env: {}

keyvault: {}

# Resources
secrets: {}
configMaps: {}
jobs: {}
cronJobs: {}
deployments: {}
services: {}
ingress: {}

# Default serviceaccount
serviceAccount: default
serviceAccounts:
  default:
    enableWorkloadIdentity: true

# Network policies
# https://docs.tigera.io/calico/latest/reference/resources/networkpolicy
network: {}

tempDirs: []