tenantId: 72fca1b1-2c2e-4376-a445-294d80196804

# Default keyvault for getting secrets
keyVaultName: bereikbaarheid-t-qstb5ip

# Identity AppID (clientId) used to authenticate with the keyvault
workloadIdentity: 88fb36b5-8b76-419a-91ae-a5868ec88f74

# We must select the nodepool to run the pods on
nodepool: cccopdrtst01

# Default host for the ingress resources
host: bereikbaarheid.opdr-t.azure.amsterdam.nl

# Specify the keyvault that has the certificate
secrets:
  certificate:
    keyVaultName: shared-t-ddxsibl3lrdai

ingress:
  app:
    className: nginx-internal